# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cuken}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hedgehog"]
  s.date = %q{2011-03-17}
  s.description = %q{Reusable Cucumber steps and API for Nagios systems testing}
  s.email = %q{hedgehogshiatus@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "cuken.gemspec",
    "features/commands.feature",
    "features/cuken.feature",
    "features/files.feature",
    "features/ssh.feature",
    "features/step_definitions/cuken_steps.rb",
    "features/support/env.rb",
    "lib/cuken.rb",
    "lib/cuken/api/cmd.rb",
    "lib/cuken/api/common.rb",
    "lib/cuken/api/file.rb",
    "lib/cuken/api/ssh.rb",
    "lib/cuken/api/ssh/password.rb",
    "lib/cuken/cmd.rb",
    "lib/cuken/common.rb",
    "lib/cuken/cucumber/cmd.rb",
    "lib/cuken/cucumber/common.rb",
    "lib/cuken/cucumber/file.rb",
    "lib/cuken/cucumber/ssh.rb",
    "lib/cuken/file.rb",
    "lib/cuken/ssh.rb",
    "spec/cuken_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/hedgehog/cuken}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Reusable Cucumber steps and API for Nagios systems testing}
  s.test_files = [
    "spec/cuken_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aruba>, ["~> 0.3.3"])
      s.add_runtime_dependency(%q<ssh-forever>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_development_dependency(%q<roodi>, ["~> 2.1.0"])
    else
      s.add_dependency(%q<aruba>, ["~> 0.3.3"])
      s.add_dependency(%q<ssh-forever>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_dependency(%q<roodi>, ["~> 2.1.0"])
    end
  else
    s.add_dependency(%q<aruba>, ["~> 0.3.3"])
    s.add_dependency(%q<ssh-forever>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.10"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<reek>, ["~> 1.2.8"])
    s.add_dependency(%q<roodi>, ["~> 2.1.0"])
  end
end

